# Créé par tomko, le 31-03-2025 en Python 3.7
# Utilisation sous demande
from turtle import*
from random import*

width_from_user=input("Define width : ")
length_from_user=input("Define length : ")
y_from_user=input("Define y : ")
x_from_user=input("Define x : ")
try:
    width_converted=int(width_from_user)
except ValueError:
    print("Warning ! You didn't typed a number !")
try:
    length_converted=int(length_from_user)
except ValueError:
    print("Warning ! You didn't typed a number !")
try:
    y_converted=int(y_from_user)
except ValueError:
    print("Warning ! You didn't typed a number !")
try:
    x_converted=int(x_from_user)
except ValueError:
    print("Warning ! You didn't typed a number !")
width(width_converted)
up()
setpos(x_converted,y_converted)

def enter():
    up()
    checkpos=(ycor())
    setpos(x_converted,checkpos-length_converted*1.5)

def initialize():
    down()
    setheading(0)
    start_position=(position())

def half_circle():
   down()
   setheading(0)
   for i in range(9):
    forward(length_converted/10)
    right(22)

def A():
    down()
    setheading(0)
    start_position=(position())
    left(70)
    forward(length_converted)
    setheading(0)
    right(70)
    forward(length_converted)
    left(180)
    forward(length_converted/2)
    setheading(180)
    forward(length_converted/2.8)
    up()
    left(180)
    forward(length_converted/2.8)
    right(70)
    forward(length_converted/2)
    setheading(0)
    up()

def B():
    down()
    setheading(0)
    start_position=(position())
    left(90)
    forward(length_converted)
    half_circle()
    half_circle()
    up()
    setheading(0)
    forward(length_converted/4)

def C():
    down()
    up()
    setheading(0)
    start_position=(position())
    forward(length_converted/3)
    down()
    setheading(-180)
    for i in range(9):
        forward(length_converted/5)
        right(22)
    up()
    setpos(start_position)
    setheading(0)
    forward(length_converted/2)

def D():
    down()
    setheading(0)
    start_position=(position())
    for i in range(9):
        forward(length_converted/5)
        left(22)
    setheading(-90)
    forward(length_converted)
    setpos(start_position)
    up()
    setheading(0)
    forward(length_converted/2)

def E():
    down()
    setheading(0)
    start_position=(position())
    forward(length_converted/2)
    setpos(start_position)
    left(90)
    forward(length_converted/2)
    setheading(0)
    forward(length_converted/2)
    left(180)
    forward(length_converted/2)
    right(90)
    forward(length_converted/2)
    right(90)
    forward(length_converted/2)
    up()
    setpos(start_position)
    setheading(0)
    forward(length_converted/2)

def F():
    down()
    setheading(0)
    start_position=(position())
    left(90)
    forward(length_converted/2)
    right(90)
    forward(length_converted/2)
    right(180)
    forward(length_converted/2)
    right(90)
    forward(length_converted/2)
    right(90)
    forward(length_converted/2)
    up()
    setpos(start_position)
    setheading(0)
    forward(length_converted/2)

def G():
    down()
    setheading(0)
    up()
    forward(length_converted/2)
    start_position=(position())
    down()
    setheading(180)
    for i in range(9):
        forward(length_converted/5)
        right(22)
    up()
    setpos(start_position)
    setheading(0)
    down()
    left(90)
    forward(length_converted/3)
    left(90)
    forward(length_converted/4)
    up()
    setpos(start_position)
    setheading(0)

def H():
    down()
    setheading(0)
    start_position=(position())
    left(90)
    forward(length_converted)
    left(180)
    forward(length_converted/2)
    setheading(0)
    forward(length_converted/2)
    left(90)
    forward(length_converted/2)
    left(180)
    forward(length_converted)
    up()

def I():
    down()
    setheading(0)
    up()
    forward(length_converted/4)
    start_position=(position())
    down()
    left(90)
    forward(length_converted)
    left(90)
    forward(length_converted/4)
    left(180)
    forward(length_converted/2)
    up()
    setpos(start_position)
    down()
    setheading(180)
    forward(length_converted/4)
    left(180)
    forward(length_converted/2)

def J(): # NTM CHRISTOPHE AVEC TON PTN DE J DE MERDE
    down()
    setheading(0)
    start_position=(position())
    setheading(180)
    for i in range(2):
        right(22)
        forward(length_converted/10)
    up()
    setpos(start_position)
    down()
    setheading(0)
    for i in range(4):
        forward(length_converted/10)
        left(22)
    up()
    setheading(90)
    down()
    for i in range(5):
        forward(length_converted/6)
    setheading(0)
    forward(length_converted/4)
    left(180)
    forward(length_converted/2)
    up()
    setpos(start_position)
    setheading(0)
    forward(length_converted/2)

def K():
    down()
    setheading(0)
    start_position=(position())
    left(90)
    forward(length_converted/1.7)
    right(45)
    forward(length_converted/1.7)
    left(180)
    forward(length_converted/2)
    setheading(0)
    right(60)
    forward(length_converted/1.36)
    up()
    setpos(start_position)
    setheading(90)
    down()
    forward(length_converted)
    up()
    setpos(start_position)
    setheading(0)
    forward(length_converted/2)

def L():
    down()
    setheading(0)
    start_position=(position())
    forward(length_converted/2)
    setpos(start_position)
    left(90)
    forward(length_converted)
    setpos(start_position)
    setheading(0)
    up()
    forward(length_converted/2)

def M():
    down()
    setheading(0)
    start_position=(position())
    left(90)
    forward(length_converted)
    setheading(0)
    right(60)
    forward(length_converted)
    setheading(0)
    left(60)
    forward(length_converted)
    setheading(0)
    right(90)
    forward(length_converted)

def N():
    down()
    setheading(0)
    start_position=(position())
    left(90)
    forward(length_converted)
    setheading(0)
    right(60)
    forward(length_converted*1.13)
    setheading(0)
    left(90)
    forward(length_converted)
    up()
    setpos(start_position)
    setheading(0)
    forward(length_converted/2)

def O():
    down()
    up()
    setheading(0)
    forward(length_converted/2)
    start_position=(position())
    up()
    left(90)
    forward(length_converted/3.5)
    down()
    setheading(-90)
    for i in range(9):
        forward(length_converted/10)
        right(22)
    setheading(90)
    forward(length_converted/2.35)
    for i in range(9):
        forward(length_converted/10)
        right(22)
    setheading(-90)
    forward(length_converted/2)
    up()
    setheading(0)
    setpos(start_position)

def P():
    down()
    setheading(0)
    start_position=(position())
    left(90)
    forward(length_converted)
    right(90)
    forward(length_converted/10)
    left(90)
    half_circle()
    setheading(180)
    forward(length_converted/10)
    up()
    setheading(0)
    setpos(start_position)
    forward(length_converted/3)

def Q():
    O()
    down()
    setheading(0)
    start_position=(position())
    left(135)
    forward(length_converted/4)
    up()
    setheading(0)
    setpos(start_position)

def R():
    down()
    setheading(0)
    start_position=(position())
    left(90)
    forward(length_converted)
    right(90)
    forward(length_converted/10)
    left(90)
    half_circle()
    setheading(180)
    forward(length_converted/10)
    setheading(0)
    forward(length_converted/7)
    right(65)
    forward(length_converted/2)
    up()
    setheading(0)
    setpos(start_position)
    forward(length_converted/3.5)

def S():
    down()
    setheading(0)
    up()
    start_position=(position())
    forward(length_converted/3)
    left(90)
    forward(length_converted)
    down()
    setheading(180)
    left(-10)
    for i in range(9):
        forward(length_converted/10)
        left(22)
    right(20)
    for i in range(9):
        forward(length_converted/10)
        right(22)
    setheading(0)
    up()
    setpos(start_position)
    forward(length_converted/2)

def T():
    down()
    up()
    setheading(0)
    forward(length_converted/3)
    down()
    start_position=(position())
    left(90)
    forward(length_converted)
    left(90)
    forward(length_converted/3)
    setheading(0)
    forward(length_converted/1.5)
    setheading(0)
    up()
    setpos(start_position)
    forward(length_converted/2)

def U():
    down()
    up()
    forward(length_converted/2)
    start_position=(position())
    up()
    left(90)
    forward(length_converted/3.5)
    down()
    setheading(-90)
    for i in range(9):
        forward(length_converted/10)
        right(22)
    setheading(90)
    forward(length_converted*0.7)
    up()
    setpos(start_position)
    forward(length_converted/6)
    down()
    forward(length_converted*0.8)
    setheading(0)
    up()
    setpos(start_position)

def V():
    down()
    setheading(0)
    start_position=(position())
    up()
    left(90)
    forward(length_converted)
    down()
    setheading(0)
    right(65)
    forward(length_converted*1.1)
    setheading(0)
    left(65)
    forward(length_converted*1.1)
    setheading(0)
    up()
    setpos(start_position)
    forward(length_converted)

def W():
    down()
    setheading(0)
    start_position=(position())
    up()
    left(90)
    forward(length_converted)
    down()
    setheading(0)
    right(75)
    forward(length_converted*1.1)
    setheading(0)
    left(75)
    forward(length_converted*1.1)
    setheading(0)
    right(75)
    forward(length_converted*1.1)
    setheading(0)
    left(75)
    forward(length_converted*1.1)
    setheading(0)
    up()
    setpos(start_position)
    forward(length_converted)

def X():
    down()
    setheading(0)
    start_position=(position())
    up()
    left(90)
    forward(length_converted)
    setheading(0)
    right(55)
    down()
    forward(length_converted*1.25)
    setheading(90)
    up()
    forward(length_converted)
    setheading(180)
    left(55)
    down()
    forward(length_converted*1.25)
    setheading(0)
    up()
    setpos(start_position)
    forward(length_converted*0.9)

def Y():
    down()
    setheading(0)
    start_position=(position())
    up()
    forward(length_converted/4)
    down()
    left(90)
    forward(length_converted/2)
    Y_position=(position())
    left(40)
    forward(length_converted/1.6)
    up()
    setpos(Y_position)
    setheading(90)
    down()
    right(40)
    forward(length_converted/1.6)
    setheading(0)
    up()
    setpos(start_position)
    forward(length_converted/2)

def Z():
    down()
    setheading(0)
    start_position=(position())
    up()
    left(90)
    forward(length_converted)
    down()
    setheading(0)
    forward(length_converted/1.5)
    right(122.5)
    forward(length_converted*1.15)
    setheading(0)
    forward(length_converted/1.5)
    up()
    setpos(start_position)
    forward(length_converted/1.5)

def space():
    up()
    setheading(0)
    forward(length_converted/4)


